version: '3'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,lambda,cloudformation,cloudwatch,sts,iam,dynamodb
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  backend:
    build: .
    environment:
      - AWS_ACCESS_KEY_ID=123
      - AWS_SECRET_ACCESS_KEY=456
      - ENDPOINT_URL=http://192.168.1.101:4566 #coloque seu ip aqui
      - APP_ENV=dev
    volumes:
      - .:/app
    ports:
      - "5000:5000"
      - "8000:80"

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
        - "8080:8080"
    volumes:
        - .:/usr/share/nginx/html/doc
    environment:
        API_URL: doc/swagger.yaml