openapi: 3.0.0

info:
  title: API s3-explorer
  version: 1.0.0
  
servers:
  - url: http://localhost:5000
  
components:
  parameters:
    ID:
      in: path
      name: id
      required: true
      schema:
        type: integer
        minimum: 1
  schemas:
    Buckets:
      type: array
      items:
        type: string
    ErrorResponse:
      type: object
      properties:
        message:
          type: string

paths:
  /api/get_buckets:
    get:
      summary: Retorna uma lista de Buckets
      description: Retorna todos os buckets permitidos 
      responses:
        200:
          description: Retorna a lista de buckets
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Buckets'
              examples:
                user:
                  summary: User Exemple
                  externalValue: 'https://foo.bar/exemples/user-exemple.json'
